version: "3"
services:
  minecraft:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 7867:7867
    env_file:
      - .env
    tty: true
    stdin_open: true
    restart: on-failure:3
    volumes:
      - ./data:/data
      - ./plugins:/data/plugins
