version: "3"
services:
  minecraft:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.20.2"
      TYPE: "PAPER"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      MOTD: "Servercito pa los cuates"
      DIFFICULTY: hard
      VIEW_DISTANCE: 20
      ICON: "https://raw.githubusercontent.com/reyes256/minecraft-server/main/server-icon.png"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
