version: "3"

services:
  mc:
    container_name: "mc-server"
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: "1.19.4"
      TYPE: "FORGE"
      FORGE_VERSION: "45.0.66"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "3G"
      MOTD: "Servercito pa los cuates"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data